spring:
  datasource:
    #    Cloud Database properties
    #    url: jdbc:postgresql://containers-us-west-206.railway.app:6943/railway
    #    username: postgres
    #    password: 0iXvBc5scFW8iRkJ5UGa

    url: jdbc:postgresql://localhost:5432/Movie-Show-Review
    username: postgres
    password: Suryansh@1904
  #    datasource:
  #      url: jdbc:h2:mem:testdb
  #      driver-class-name: org.h2.Driver
  #      username: sa
  #      password: sa
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: suryanshsharmab@gmail.com
    password: fmpfxmyxwybmthje
    port: '587'
